### ISSUE TITLE
Hello Sidewalk friend!!

### ISSUE THREAD

**Issue by kauevestena** [CurtisGreen/opensidewalkmap#1]
Well, I'm not one of those that think that one could be owner of a name for a project.

Then it's just as a matter of communication: [https://kauevestena.github.io/opensidewalkmap/](https://kauevestena.github.io/opensidewalkmap/) that I have a project with the same name since 2022, so I think that we can cooperate!

repo link: https://github.com/kauevestena/opensidewalkmap 

All the best,
Kauê

**Comment by CurtisGreen** [comment]
> Well, I'm not one of those that think that one could be owner of a name for a project.
> 
> Then it's just as a matter of communication: https://kauevestena.github.io/opensidewalkmap/ that I have a project with the same name since 2022, so I think that we can cooperate!
> 
> repo link: https://github.com/kauevestena/opensidewalkmap
> 
> All the best, Kauê

Hi Kauê,

I agree it’s a bit confusing but that wasn’t my intention. This was forked off of open parking map so I simply called it open sidewalk map. 

Cooperating sounds great though, let me know if there’s anything that would be helpful to pedestrians that I can work on. Recently I haven’t been updating the website but instead adding sidewalks to my area though OSM

To reduce confusion I can add something like, “if you’re looking for ___ then go here”. Or “not to be confused with ___” to my readme. Let me know how you would like your project described, or you can create a PR to update it

**Comment by kauevestena** [comment]
Ahh, no problem at all!

If you're interested in sidewalk mapping, I have created a plugin for the generation of sidewalk geometries for OSM: https://github.com/kauevestena/osm_sidewalkreator 

It works in quite a nifty way for regularly shaped cities!

Well, I invite you to visit the OSWM ecosystem, there's a TODO file with many stuff to be accomplished (Particularly I need some help on doing an MapLibre-based interactive static webmap view)
Codebase (the todo file directly): https://github.com/kauevestena/oswm_codebase/blob/main/todo
Main Repository: https://github.com/kauevestena/opensidewalkmap
The first node: https://github.com/kauevestena/opensidewalkmap_beta

It will be very interesting! I think that I can do the PR!


Thanks a lot.

**Comment by CurtisGreen** [comment]
I'm not familiar with MapLibre but I'll take a look 👍

**Comment by CurtisGreen** [comment]
> I'm not familiar with MapLibre but I'll take a look 👍

@kauevestena FYI, since it has been 3 weeks. I did take a look through the project to see if there was something I could be helpful on but I didn't notice anything I'm familiar with so I wasn't exactly sure where to enter. I did just refer some interested sidewalk mappers to your sidewalk creator program github page so hopefully they can further the cause https://github.com/CurtisGreen/opensidewalkmap/issues/3
